from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(slots=True)
class BlueprintResult:
    root: Path
    files: list[Path]
    stack: str


class StackBlueprints:
    def create_fastapi_service(self, root: Path, name: str = 'service') -> BlueprintResult:
        project_root = root / name
        files = {
            'README.md': self._fastapi_readme(name),
            'pyproject.toml': self._fastapi_pyproject(name),
            'app/__init__.py': '',
            'app/main.py': self._fastapi_main(),
            'app/settings.py': self._fastapi_settings(),
            'app/schemas.py': self._fastapi_schemas(),
            'app/services.py': self._fastapi_services(),
            'tests/test_health.py': self._fastapi_tests(),
        }
        return self._write(project_root, files, 'fastapi')

    def create_react_vite_app(self, root: Path, name: str = 'web-app') -> BlueprintResult:
        project_root = root / name
        files = {
            'README.md': self._react_readme(name),
            'package.json': self._react_package(name),
            'index.html': "<div id=\"root\"></div><script type=\"module\" src=\"/src/main.tsx\"></script>\n",
            'src/main.tsx': self._react_main(),
            'src/App.tsx': self._react_app(),
            'src/App.test.tsx': self._react_test(),
            'src/styles.css': self._react_css(),
            'vite.config.ts': self._vite_config(),
            'tsconfig.json': self._tsconfig(),
        }
        return self._write(project_root, files, 'react-vite')

    def _write(self, project_root: Path, files: dict[str, str], stack: str) -> BlueprintResult:
        written: list[Path] = []
        for relative_path, content in files.items():
            path = project_root / relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
            written.append(path)
        return BlueprintResult(project_root, written, stack)

    def _fastapi_readme(self, name: str) -> str:
        return f"# {name}\n\nFastAPI service generated by GitHub AI Genius.\n\nRun tests with `pytest`. Run locally with `uvicorn app.main:app --reload`.\n"

    def _fastapi_pyproject(self, name: str) -> str:
        return f"[project]\nname = \"{name}\"\nversion = \"1.0.0\"\nrequires-python = \">=3.11\"\ndependencies = [\"fastapi>=0.115.0\", \"uvicorn[standard]>=0.30.6\", \"pydantic-settings>=2.4.0\"]\n\n[project.optional-dependencies]\ndev = [\"pytest>=8.3.2\", \"httpx>=0.27.0\"]\n"

    def _fastapi_main(self) -> str:
        return "from fastapi import FastAPI\nfrom .schemas import HealthResponse\nfrom .services import SystemService\n\napp = FastAPI(title='Generated FastAPI Service', version='1.0.0')\nservice = SystemService()\n\n@app.get('/health', response_model=HealthResponse)\ndef health():\n    return service.health()\n"

    def _fastapi_settings(self) -> str:
        return "from pydantic_settings import BaseSettings\n\nclass Settings(BaseSettings):\n    app_name: str = 'Generated FastAPI Service'\n    environment: str = 'local'\n"

    def _fastapi_schemas(self) -> str:
        return "from pydantic import BaseModel\n\nclass HealthResponse(BaseModel):\n    ok: bool\n    service: str\n"

    def _fastapi_services(self) -> str:
        return "class SystemService:\n    def health(self):\n        return {'ok': True, 'service': 'generated-fastapi-service'}\n"

    def _fastapi_tests(self) -> str:
        return "from fastapi.testclient import TestClient\nfrom app.main import app\n\ndef test_health():\n    client = TestClient(app)\n    response = client.get('/health')\n    assert response.status_code == 200\n    assert response.json()['ok'] is True\n"

    def _react_readme(self, name: str) -> str:
        return f"# {name}\n\nReact Vite application generated by GitHub AI Genius.\n\nRun `npm install`, `npm test`, and `npm run dev`.\n"

    def _react_package(self, name: str) -> str:
        return '{"name":"' + name + '","version":"1.0.0","private":true,"type":"module","scripts":{"dev":"vite","build":"tsc && vite build","test":"vitest run"},"dependencies":{"@vitejs/plugin-react":"latest","vite":"latest","typescript":"latest","react":"latest","react-dom":"latest"},"devDependencies":{"vitest":"latest","@testing-library/react":"latest","@testing-library/jest-dom":"latest","jsdom":"latest"}}\n'

    def _react_main(self) -> str:
        return "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport './styles.css';\nimport { App } from './App';\n\ncreateRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);\n"

    def _react_app(self) -> str:
        return "export function App() {\n  return <main className=\"shell\"><h1>Generated React Application</h1><p>Production scaffold is ready for feature modules.</p></main>;\n}\n"

    def _react_test(self) -> str:
        return "import { render, screen } from '@testing-library/react';\nimport { App } from './App';\n\ntest('renders generated application', () => {\n  render(<App />);\n  expect(screen.getByText('Generated React Application')).toBeTruthy();\n});\n"

    def _react_css(self) -> str:
        return "body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #0f172a; color: #f8fafc; } .shell { min-height: 100vh; display: grid; place-content: center; text-align: center; padding: 2rem; }\n"

    def _vite_config(self) -> str:
        return "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()], test: { environment: 'jsdom' } });\n"

    def _tsconfig(self) -> str:
        return '{"compilerOptions":{"target":"ES2020","useDefineForClassFields":true,"lib":["DOM","DOM.Iterable","ES2020"],"allowJs":false,"skipLibCheck":true,"esModuleInterop":true,"allowSyntheticDefaultImports":true,"strict":true,"forceConsistentCasingInFileNames":true,"module":"ESNext","moduleResolution":"Node","resolveJsonModule":true,"isolatedModules":true,"noEmit":true,"jsx":"react-jsx"},"include":["src"],"references":[]}\n'
