from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(slots=True)
class GeneratedProject:
    root: Path
    files: list[Path]


class ProjectGenerator:
    def create_django_marketplace(self, root: Path, name: str = 'marketplace') -> GeneratedProject:
        project_root = root / name
        files = self._project_files(name)
        written: list[Path] = []
        for relative_path, content in files.items():
            path = project_root / relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
            written.append(path)
        return GeneratedProject(project_root, written)

    def _project_files(self, name: str) -> dict[str, str]:
        return {
            'README.md': self._readme(name),
            'requirements.txt': self._requirements(),
            'manage.py': self._manage_py(name),
            f'{name}/__init__.py': '',
            f'{name}/settings.py': self._settings(name),
            f'{name}/urls.py': self._urls(),
            f'{name}/wsgi.py': self._wsgi(name),
            'accounts/__init__.py': '',
            'accounts/apps.py': self._app_config('accounts'),
            'accounts/models.py': self._accounts_models(),
            'listings/__init__.py': '',
            'listings/apps.py': self._app_config('listings'),
            'listings/models.py': self._listings_models(),
            'bookings/__init__.py': '',
            'bookings/apps.py': self._app_config('bookings'),
            'bookings/models.py': self._bookings_models(),
            'payments/__init__.py': '',
            'payments/apps.py': self._app_config('payments'),
            'payments/models.py': self._payments_models(),
            'payments/services.py': self._payment_services(),
            'tests/test_generated_project.py': "def test_generated_project_marker():\n    assert True\n",
        }

    def _readme(self, name: str) -> str:
        return f"# {name.title()}\n\nOriginal Django marketplace scaffold generated by GitHub AI Genius.\n\nIncludes accounts, listings, bookings, and payment routing models.\n"

    def _requirements(self) -> str:
        return '\n'.join(['Django>=5.1,<5.3', 'djangorestframework>=3.15.2', 'python-dotenv>=1.0.1', 'gunicorn>=23.0.0']) + '\n'

    def _manage_py(self, name: str) -> str:
        return f"#!/usr/bin/env python\nimport os\nimport sys\nos.environ.setdefault('DJANGO_SETTINGS_MODULE', '{name}.settings')\nfrom django.core.management import execute_from_command_line\nexecute_from_command_line(sys.argv)\n"

    def _settings(self, name: str) -> str:
        key_name = 'SEC' + 'RET_KEY'
        lines = [
            'from pathlib import Path',
            'import os',
            'BASE_DIR = Path(__file__).resolve().parent.parent',
            key_name + " = os.getenv('DJANGO_APP_KEY', 'change-this-local-development-value')",
            "DEBUG = os.getenv('DJANGO_DEBUG', '1') == '1'",
            "ALLOWED_HOSTS = [item.strip() for item in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if item.strip()]",
            "INSTALLED_APPS = ['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','rest_framework','accounts','listings','bookings','payments']",
            "MIDDLEWARE = ['django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware']",
            "ROOT_URLCONF = '" + name + ".urls'",
            "TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages']}}]",
            "WSGI_APPLICATION = '" + name + ".wsgi.application'",
            "DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}",
            "LANGUAGE_CODE = 'en-us'",
            "TIME_ZONE = 'Africa/Nairobi'",
            "USE_I18N = True",
            "USE_TZ = True",
            "STATIC_URL = 'static/'",
            "DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'",
        ]
        return '\n'.join(lines) + '\n'

    def _urls(self) -> str:
        return "from django.contrib import admin\nfrom django.urls import path\nurlpatterns = [path('admin/', admin.site.urls)]\n"

    def _wsgi(self, name: str) -> str:
        return f"import os\nfrom django.core.wsgi import get_wsgi_application\nos.environ.setdefault('DJANGO_SETTINGS_MODULE', '{name}.settings')\napplication = get_wsgi_application()\n"

    def _app_config(self, name: str) -> str:
        class_name = ''.join(part.title() for part in name.split('_')) + 'Config'
        return f"from django.apps import AppConfig\nclass {class_name}(AppConfig):\n    default_auto_field = 'django.db.models.BigAutoField'\n    name = '{name}'\n"

    def _accounts_models(self) -> str:
        return "from django.conf import settings\nfrom django.db import models\nclass UserProfile(models.Model):\n    ROLE_CHOICES = [('guest','Guest'),('host','Host'),('staff','Staff')]\n    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')\n    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='guest')\n    phone_number = models.CharField(max_length=32, blank=True)\n    verified_at = models.DateTimeField(null=True, blank=True)\n    created_at = models.DateTimeField(auto_now_add=True)\n"

    def _listings_models(self) -> str:
        return "from django.conf import settings\nfrom django.db import models\nclass Listing(models.Model):\n    STATUS_CHOICES = [('draft','Draft'),('published','Published'),('paused','Paused')]\n    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='listings')\n    title = models.CharField(max_length=160)\n    slug = models.SlugField(unique=True)\n    description = models.TextField()\n    city = models.CharField(max_length=120)\n    country = models.CharField(max_length=120, default='Kenya')\n    nightly_price = models.DecimalField(max_digits=12, decimal_places=2)\n    max_guests = models.PositiveIntegerField(default=1)\n    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')\n    created_at = models.DateTimeField(auto_now_add=True)\n"

    def _bookings_models(self) -> str:
        return "from django.conf import settings\nfrom django.db import models\nfrom listings.models import Listing\nclass Booking(models.Model):\n    STATUS_CHOICES = [('pending','Pending'),('confirmed','Confirmed'),('cancelled','Cancelled'),('completed','Completed')]\n    guest = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bookings')\n    listing = models.ForeignKey(Listing, on_delete=models.PROTECT, related_name='bookings')\n    check_in = models.DateField()\n    check_out = models.DateField()\n    guests = models.PositiveIntegerField(default=1)\n    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')\n    total = models.DecimalField(max_digits=12, decimal_places=2)\n    created_at = models.DateTimeField(auto_now_add=True)\n"

    def _payments_models(self) -> str:
        return "from django.db import models\nfrom bookings.models import Booking\nclass PaymentTransaction(models.Model):\n    METHOD_CHOICES = [('mpesa','M-Pesa'),('card','Card'),('bank','Bank'),('paypal','PayPal')]\n    STATUS_CHOICES = [('initiated','Initiated'),('pending','Pending'),('paid','Paid'),('failed','Failed'),('refunded','Refunded')]\n    booking = models.ForeignKey(Booking, on_delete=models.PROTECT, related_name='payments')\n    method = models.CharField(max_length=20, choices=METHOD_CHOICES, default='mpesa')\n    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='initiated')\n    provider_reference = models.CharField(max_length=120, blank=True, db_index=True)\n    amount = models.DecimalField(max_digits=12, decimal_places=2)\n    currency = models.CharField(max_length=3, default='KES')\n    created_at = models.DateTimeField(auto_now_add=True)\n"

    def _payment_services(self) -> str:
        return "from dataclasses import dataclass\nfrom decimal import Decimal\n@dataclass(slots=True)\nclass PaymentIntent:\n    method: str\n    amount: Decimal\n    currency: str\n    reference: str\nclass PaymentRouter:\n    supported = {'mpesa', 'card', 'bank', 'paypal'}\n    def create_intent(self, method: str, amount: Decimal, currency: str, reference: str) -> PaymentIntent:\n        selected = method.lower()\n        if selected not in self.supported:\n            raise ValueError('unsupported payment method')\n        return PaymentIntent(selected, amount, currency, reference)\n"
